import fs from "node:fs";
import admin from "firebase-admin";
import { FieldValue, getFirestore } from "firebase-admin/firestore";

const credentialsPath = process.env.GOOGLE_APPLICATION_CREDENTIALS;
if (!credentialsPath) throw new Error("Defina GOOGLE_APPLICATION_CREDENTIALS apontando para a Service Account local.");
const serviceAccount = JSON.parse(fs.readFileSync(credentialsPath, "utf8"));
if (serviceAccount.project_id !== "donos-b59bd") throw new Error("Seed bloqueado: o projeto precisa ser donos-b59bd.");
admin.initializeApp({ credential: admin.cert(serviceAccount), projectId: "donos-b59bd" });
const db = getFirestore();
const now = FieldValue.serverTimestamp();

const content = [
  {
    id: "metodo-sites-empresas-locais", title: "Criação de sites para empresas locais", category: "Métodos de renda", order: 1,
    description: "Aprenda a oferecer sites simples e úteis para negócios que precisam ser encontrados e contatados online.",
    introduction: "Muitos negócios locais têm bons produtos, mas não apresentam seus serviços de forma clara na internet. Um site enxuto pode organizar informações, gerar confiança e facilitar pedidos de orçamento. O objetivo não é prometer vendas automáticas: é entregar uma presença digital funcional.",
    steps: ["Escolha um nicho, como salões, restaurantes, profissionais liberais ou lojas de bairro.", "Monte um exemplo demonstrativo com serviços, fotos autorizadas, localização e botão de contato.", "Defina uma oferta com escopo fechado: página inicial, serviços, contato, mapa e versão mobile.", "Pesquise empresas no Google Maps e redes sociais, observando sites ausentes ou desatualizados.", "Aborde com uma observação específica e ofereça mostrar uma ideia visual sem compromisso.", "Registre escopo, prazo, revisões, hospedagem e manutenção antes de começar."],
    examples: "Oferta exemplo: site institucional de uma página, formulário ou WhatsApp, mapa, SEO básico e publicação. Faixa inicial sugerida: R$ 600 a R$ 1.800, ajustada ao escopo, prazo e suporte. Manutenção opcional: R$ 80 a R$ 250 por mês.",
    tips: ["Mostre uma demonstração no celular.", "Cobre sinal antes de iniciar.", "Use imagens e textos autorizados pelo cliente.", "Entregue uma lista clara do que está e não está incluído."],
    commonMistakes: ["Prometer primeira posição no Google.", "Aceitar alterações ilimitadas.", "Começar sem definir quem fornece textos, fotos e domínio.", "Ignorar acessibilidade e carregamento no celular."],
    conclusion: "Comece com uma oferta pequena e repetível. O primeiro objetivo é aprender a entregar bem, criar portfólio autorizado e transformar o processo em um serviço previsível.", active: true
  },
  {
    id: "metodo-artes-anuncios", title: "Criação de artes e anúncios", category: "Métodos de renda", order: 2,
    description: "Transforme briefing, identidade visual e informação de oferta em peças prontas para divulgação.",
    introduction: "Pequenos negócios precisam comunicar promoções, novidades e serviços com clareza. Você pode vender peças avulsas ou pacotes mensais, desde que combine formatos, prazos e revisões.",
    steps: ["Escolha formatos que o cliente realmente usa: post, story, capa, card de preço ou anúncio.", "Peça objetivo, público, oferta, identidade visual, imagens autorizadas e chamada para ação.", "Crie duas ou três variações de composição, mantendo hierarquia visual e contraste.", "Use IA para rascunhar ideias e textos, mas revise informações, ortografia e direitos de imagem.", "Monte pacotes com quantidade de peças, prazo de aprovação e número de revisões.", "Apresente uma prévia com marca d'água e entregue arquivos finais após o combinado."],
    examples: "Pacote inicial: 8 posts e 12 stories por R$ 350 a R$ 900, conforme complexidade e acompanhamento. Uma arte avulsa pode ser precificada entre R$ 40 e R$ 180 como referência de partida, não como tabela fixa.",
    tips: ["Crie um formulário de briefing.", "Separe texto, imagem e chamada para ação.", "Nomeie arquivos por data e formato.", "Faça revisão final em tela de celular."],
    commonMistakes: ["Copiar identidade de concorrente.", "Usar imagem sem licença.", "Entregar arquivo editável sem combinar isso.", "Confundir quantidade de peças com quantidade de conceitos."],
    conclusion: "Uma boa arte resolve uma comunicação específica. Venda clareza e consistência, não apenas horas de edição.", active: true
  },
  {
    id: "metodo-servicos-ia", title: "Serviços com inteligência artificial", category: "Métodos de renda", order: 3,
    description: "Use IA como acelerador para entregar pesquisa, rascunho e organização com revisão humana.",
    introduction: "IA pode reduzir o tempo de tarefas repetitivas, mas o valor do serviço está no entendimento do problema, na curadoria e na revisão. Nunca entregue uma saída automática sem conferir fatos, tom e adequação ao cliente.",
    steps: ["Liste tarefas de negócios que consomem tempo: descrições, FAQs, roteiros, planilhas ou ideias.", "Escolha uma entrega com começo, meio e fim, como 20 descrições revisadas ou um calendário editorial.", "Crie um fluxo: briefing, geração, checagem, edição, aprovação e entrega.", "Teste ferramentas e registre limites, custos e necessidade de revisão.", "Monte uma amostra antes/depois que mostre ganho de clareza, não promessa de lucro.", "Precifique pela responsabilidade e resultado do trabalho, não somente pelo tempo de digitação."],
    examples: "Oferta exemplo: calendário com 20 ideias, legendas revisadas e chamadas para ação por R$ 250 a R$ 700, dependendo da pesquisa e do nicho.",
    tips: ["Não envie dados confidenciais para ferramentas sem autorização.", "Peça referências de tom de voz.", "Verifique nomes, números e promessas.", "Mantenha um checklist de qualidade."],
    commonMistakes: ["Publicar texto sem revisão.", "Prometer automação total.", "Usar dados pessoais do cliente sem cuidado.", "Vender uma ferramenta em vez de vender uma entrega."],
    conclusion: "A vantagem competitiva não é apertar um botão: é transformar uma saída genérica em material útil, correto e alinhado ao contexto.", active: true
  },
  {
    id: "metodo-afiliados", title: "Marketing de afiliados", category: "Métodos de renda", order: 4,
    description: "Entenda como divulgar produtos de terceiros com transparência, conteúdo útil e acompanhamento de métricas.",
    introduction: "No marketing de afiliados, você recebe comissão quando uma venda elegível acontece pelo seu link. O resultado depende de produto, audiência, confiança, oferta e consistência; não existe garantia de renda.",
    steps: ["Escolha um tema que você consegue estudar e explicar com honestidade.", "Compare produtos por suporte, política de comissão, reputação e aderência ao público.", "Leia as regras do programa e sinalize claramente quando houver link de afiliado.", "Crie conteúdo que ajude a decidir: comparação, tutorial, checklist ou análise de uso.", "Use uma página ou planilha para organizar links e origem das visitas.", "Acompanhe cliques, conversões e dúvidas para melhorar o conteúdo sem insistência."],
    examples: "Estratégia orgânica: publicar um tutorial semanal, responder dúvidas reais e incluir um convite transparente para conhecer o produto. Não copie avaliações nem invente resultados.",
    tips: ["Priorize confiança de longo prazo.", "Teste ou pesquise antes de recomendar.", "Respeite regras de cada rede.", "Diversifique canais sem fazer spam."],
    commonMistakes: ["Prometer ganhos garantidos.", "Esconder que o link gera comissão.", "Enviar mensagens em massa.", "Escolher produto apenas pela comissão."],
    conclusion: "Afiliado sustentável educa antes de indicar. Construa um acervo de conteúdo útil e trate métricas como aprendizado, não como promessa.", active: true
  },
  {
    id: "metodo-conteudo-empresas", title: "Criação de conteúdo para empresas", category: "Métodos de renda", order: 5,
    description: "Planeje posts, reels, vídeos e legendas em pacotes que ajudam negócios a comunicar melhor suas ofertas.",
    introduction: "Empresas costumam ter conhecimento do próprio negócio, mas falta tempo para transformar isso em conteúdo. Seu papel é organizar pauta, produção e aprovação com consistência.",
    steps: ["Faça uma reunião curta para entender público, diferenciais, ofertas e restrições.", "Monte quatro pilares de conteúdo: educação, prova, bastidores e oferta.", "Defina formatos e volume mensal: posts, reels, stories, roteiros e legendas.", "Crie um calendário com datas de gravação, aprovação e publicação.", "Produza roteiros simples e deixe claro o que depende do cliente, como gravações.", "Entregue relatório básico com peças produzidas, alcance disponível e próximos testes."],
    examples: "Pacote inicial: 8 posts, 4 roteiros de reels e 12 ideias de stories por R$ 600 a R$ 1.500, variando conforme captação, edição e estratégia.",
    tips: ["Use um quadro de aprovação.", "Reserve uma margem para imprevistos.", "Peça autorização para usar trabalhos no portfólio.", "Diferencie produção de publicação e gestão de anúncios."],
    commonMistakes: ["Prometer viralização.", "Fazer calendário sem objetivo.", "Publicar sem revisão do cliente.", "Incluir gravação e edição complexa sem precificar."],
    conclusion: "Conteúdo bom nasce de uma estratégia simples e de um processo de aprovação claro. Comece com um pacote que você consiga entregar com qualidade.", active: true
  },
  {
    id: "ia-sites", title: "Como usar IA para criar sites", category: "Central de IA", order: 11,
    description: "Use IA para transformar briefing em estrutura, textos e checklist de um site, mantendo revisão humana.",
    introduction: "A IA pode ajudar a pesquisar perguntas frequentes, organizar páginas e rascunhar textos. Ela não substitui a validação do negócio, do cliente e das informações legais.",
    steps: ["Colete objetivo, público, serviços, diferenciais e chamada para ação.", "Peça um mapa de páginas e campos necessários.", "Gere rascunhos de títulos, benefícios e perguntas frequentes.", "Revise fatos, tom, acessibilidade e consentimento para imagens.", "Implemente uma versão mobile e teste links, formulários e velocidade.", "Mostre ao cliente e registre as alterações aprovadas."],
    examples: "Peça à IA três estruturas para uma página de fisioterapia, depois escolha a mais simples e valide cada afirmação com o profissional.", tips: ["Use contexto real.", "Peça alternativas curtas.", "Faça revisão por seção."], commonMistakes: ["Publicar fatos inventados.", "Usar depoimentos falsos.", "Esquecer política de privacidade."], conclusion: "IA acelera rascunho; responsabilidade e decisão continuam com você e com o cliente.", active: true
  },
  {
    id: "ia-artes", title: "Como usar IA para criar artes", category: "Central de IA", order: 12,
    description: "Crie direções visuais e variações de campanha com briefing, referências e revisão de marca.",
    introduction: "IA visual é útil para explorar conceitos, mas precisa respeitar a identidade do cliente, direitos de uso e legibilidade da peça.", steps: ["Defina objetivo, formato, público e mensagem.", "Descreva paleta, clima, composição e elementos proibidos.", "Gere variações e selecione uma direção.", "Ajuste texto e hierarquia em uma ferramenta de design.", "Faça teste de leitura em 360px e revise direitos de imagem.", "Entregue arquivos no formato combinado."], examples: "Para uma cafeteria, peça três direções de campanha de inverno e depois refaça a tipografia e preços manualmente.", tips: ["Gere conceito, não arte final automática.", "Evite marcas e pessoas reconhecíveis sem autorização.", "Mantenha contraste."], commonMistakes: ["Usar texto gerado na imagem sem revisão.", "Ignorar formato de cada rede.", "Copiar estilo identificável."], conclusion: "A ferramenta abre possibilidades; o profissional transforma a ideia em comunicação correta.", active: true
  },
  {
    id: "ia-copy", title: "Como usar IA para criar textos de venda", category: "Central de IA", order: 13,
    description: "Estruture benefícios, objeções e chamadas para ação sem exageros ou promessas enganosas.",
    introduction: "Um bom texto de venda informa e ajuda a pessoa a decidir. A IA pode sugerir ângulos, mas você deve confirmar características, condições e limites da oferta.", steps: ["Informe produto, público, problema e diferencial real.", "Peça versões com diferentes níveis de formalidade.", "Solicite objeções e respostas baseadas em fatos.", "Corte exageros e transforme benefícios em exemplos concretos.", "Inclua condições, prazo e chamada para ação clara.", "Revise com o responsável pela oferta."], examples: "Para um serviço de sites, troque 'aumente suas vendas garantidamente' por 'apresente seus serviços com clareza e facilite pedidos de orçamento'.", tips: ["Peça texto simples.", "Teste títulos diferentes.", "Não esconda condições."], commonMistakes: ["Prova social inventada.", "Urgência falsa.", "Promessa de resultado garantido."], conclusion: "Clareza e honestidade convertem melhor do que exagero sustentável.", active: true
  },
  {
    id: "ia-ideias-servicos", title: "Como usar IA para encontrar ideias de serviços", category: "Central de IA", order: 14,
    description: "Descubra ofertas possíveis cruzando habilidades, problemas locais e entregas que você consegue cumprir.",
    introduction: "A IA pode ampliar possibilidades, mas a escolha precisa considerar habilidade, acesso a ferramentas, tempo, público e capacidade de entrega.", steps: ["Liste suas habilidades, equipamentos e tempo disponível.", "Escolha três nichos que você conhece ou consegue pesquisar.", "Peça problemas frequentes e entregas pequenas para cada nicho.", "Compare demanda observável, dificuldade e preço praticável.", "Converse com potenciais clientes antes de produzir um pacote.", "Faça um piloto e ajuste pelo feedback."], examples: "Cruze edição de vídeo no celular com restaurantes locais para criar um pacote de quatro vídeos curtos com roteiro e legendas.", tips: ["Valide antes de criar marca.", "Comece pequeno.", "Registre objeções."], commonMistakes: ["Escolher ideia só porque parece fácil.", "Ignorar concorrência.", "Prometer serviço que ainda não sabe entregar."], conclusion: "Ideia vira serviço quando encontra um problema real e uma entrega repetível.", active: true
  },
  {
    id: "ia-redes-sociais", title: "Como usar IA para criar conteúdo para redes sociais", category: "Central de IA", order: 15,
    description: "Planeje pautas, roteiros e legendas alinhados a objetivo, audiência e calendário editorial.",
    introduction: "IA ajuda a sair da página em branco e a variar formatos. O conteúdo precisa manter voz humana, contexto local e revisão das informações.", steps: ["Defina objetivo do mês e quatro pilares.", "Peça 20 ideias em formatos diferentes.", "Selecione ideias que o cliente consegue produzir.", "Gere roteiro, legenda e CTA para cada uma.", "Adapte linguagem e inclua exemplos reais.", "Organize aprovação e calendário."], examples: "Para uma barbearia: tutorial, bastidor, cuidado pós-corte e oferta limitada com condições claras.", tips: ["Inclua localização.", "Varie CTA.", "Analise comentários para novas pautas."], commonMistakes: ["Publicar conteúdo genérico.", "Repetir CTA em tudo.", "Usar tendências sem relação com a marca."], conclusion: "Consistência nasce de um processo simples, não de publicar qualquer coisa todos os dias.", active: true
  },
  {
    id: "cliente-encontrar-empresas", title: "Como encontrar empresas que precisam de serviços", category: "Clientes", order: 21, description: "Monte uma lista de empresas com sinais reais de necessidade e priorize contatos relevantes.", introduction: "Prospecção melhora quando você observa sinais: comunicação desatualizada, ausência de página, oferta confusa ou baixa frequência de conteúdo.", steps: ["Escolha um bairro e nicho.", "Pesquise no Google Maps, Instagram e diretórios.", "Registre nome, contato público, problema observado e prioridade.", "Separe empresas adequadas ao seu serviço.", "Personalize uma mensagem curta.", "Faça follow-up em dias diferentes sem insistência."], examples: "Observe uma clínica com perfil ativo, mas sem página de serviços; ofereça organizar informações e facilitar pedidos de orçamento.", tips: ["Use apenas contatos públicos.", "Respeite opt-out.", "Anote a data do contato."], commonMistakes: ["Disparar a mesma mensagem.", "Criticar o negócio.", "Contactar sem entender o nicho."], conclusion: "Uma lista menor e bem pesquisada costuma ser melhor que centenas de contatos aleatórios.", active: true
  },
  {
    id: "cliente-empresas-sem-site", title: "Como encontrar empresas sem site", category: "Clientes", order: 22, description: "Use buscas locais e sinais de presença digital para encontrar negócios que podem se beneficiar de um site.", introduction: "A ausência de site não significa automaticamente que uma empresa queira contratar. O papel da pesquisa é encontrar oportunidade e iniciar conversa com respeito.", steps: ["Pesquise categorias e bairros no Maps.", "Abra os perfis e marque quem não tem botão de site.", "Confira se a empresa já usa catálogo, rede social ou marketplace.", "Identifique uma melhoria específica.", "Prepare uma demonstração simples.", "Pergunte se faz sentido conversar."], examples: "Mensagem: notei que seus clientes precisam pedir informações pelo direct; posso mostrar uma página simples com serviços, localização e botão de orçamento.", tips: ["Não diga que a empresa está 'errada'.", "Mostre benefício operacional.", "Tenha uma amostra."], commonMistakes: ["Ignorar que o negócio pode não ter orçamento.", "Inventar dados sobre a empresa.", "Mandar link suspeito."], conclusion: "A melhor abordagem parte de uma melhoria observável e deixa o cliente decidir.", active: true
  },
  {
    id: "cliente-abordagem", title: "Como abordar um possível cliente", category: "Clientes", order: 23, description: "Aprenda a iniciar conversas curtas, específicas e respeitosas.", introduction: "Abordagem não é pressão. É uma pergunta contextual que abre espaço para entender se existe problema, prioridade e orçamento.", steps: ["Apresente-se em uma frase.", "Mencione algo específico que observou.", "Explique uma possibilidade de melhoria.", "Faça uma pergunta simples.", "Só envie proposta após entender o cenário.", "Registre a resposta e respeite o silêncio."], examples: "Olá, Ana. Vi que vocês divulgam os serviços pelo Instagram. Trabalho com páginas enxutas para organizar informações e pedidos de orçamento. Posso te enviar um exemplo?", tips: ["Seja breve.", "Use nome e contexto reais.", "Peça permissão para enviar material."], commonMistakes: ["Texto longo demais.", "Falar só de você.", "Enviar preço sem escopo."], conclusion: "Uma boa abordagem gera conversa, não tenta fechar tudo na primeira mensagem.", active: true
  },
  {
    id: "cliente-followup", title: "Como fazer follow-up sem ser inconveniente", category: "Clientes", order: 24, description: "Organize retornos com contexto, prazo e liberdade para a pessoa recusar.", introduction: "Follow-up é uma lembrança útil quando acrescenta contexto. Se a pessoa pedir para não receber mensagens, encerre o contato.", steps: ["Combine quando pode retornar.", "Envie uma mensagem curta com o contexto.", "Acrescente uma informação ou exemplo relevante.", "Pergunte se a prioridade mudou.", "Faça no máximo alguns contatos espaçados.", "Agradeça e encerre se não houver interesse."], examples: "Oi, Ana. Retomo o exemplo de página que enviei na terça. Separei uma versão com botão de orçamento. Se não for prioridade agora, tudo bem; posso não insistir.", tips: ["Use agenda.", "Não finja urgência.", "Dê saída clara."], commonMistakes: ["Mandar 'e aí?' repetidamente.", "Cobrar resposta.", "Fazer spam em vários canais."], conclusion: "Respeito protege sua reputação e mantém portas abertas.", active: true
  },
  {
    id: "cliente-fechar-servico", title: "Como apresentar e fechar um serviço", category: "Clientes", order: 25, description: "Transforme diagnóstico em proposta clara, com escopo, prazo, investimento e próximos passos.", introduction: "Fechamento fica mais simples quando a proposta reduz dúvidas. Ela deve registrar o que será feito, o que depende do cliente e como serão aprovadas mudanças.", steps: ["Recapitule o problema e objetivo.", "Apresente uma solução com entregáveis.", "Defina prazo, revisões e responsabilidades.", "Informe investimento e condições.", "Explique validade da proposta sem pressão artificial.", "Envie contrato ou aceite registrado e cobre o sinal combinado."], examples: "Proposta: landing page, cinco seções, formulário, versão mobile, duas revisões e publicação em até 10 dias úteis; não inclui fotos profissionais nem anúncios.", tips: ["Ofereça no máximo duas opções.", "Use linguagem simples.", "Confirme aceite por escrito."], commonMistakes: ["Escopo aberto.", "Desconto sem motivo.", "Começar sem sinal ou aceite."], conclusion: "Fechar é alinhar expectativas com clareza, não convencer alguém contra a vontade.", active: true
  },
  {
    id: "guia-primeiro-cliente", title: "Guia para conseguir o primeiro cliente", category: "Guias", order: 31, description: "Um plano prático para escolher uma oferta, criar prova e iniciar conversas reais.", introduction: "O primeiro cliente costuma vir de uma oferta pequena e específica. Você não precisa começar com uma agência completa; precisa conseguir entregar uma solução bem definida.", steps: ["Escolha uma habilidade e um nicho.", "Crie uma demonstração própria.", "Escreva uma oferta de uma página.", "Monte lista de 20 contatos públicos relevantes.", "Envie mensagens personalizadas.", "Faça follow-up respeitoso.", "Entregue um piloto e peça autorização para depoimento."], examples: "Oferta inicial: página de apresentação para profissionais autônomos, com prazo de sete dias e duas revisões.", checklist: ["Serviço definido", "Exemplo pronto", "Preço e escopo", "Lista de contatos", "Mensagem revisada", "Agenda de follow-up"], commonMistakes: ["Esperar portfólio perfeito.", "Oferecer tudo.", "Não registrar aprendizados."], tips: ["Converse com cinco pessoas antes de mudar a oferta.", "Peça feedback, não elogio."], conclusion: "O primeiro objetivo é validar uma entrega e aprender a vender com honestidade.", active: true
  },
  {
    id: "guia-vender-site", title: "Guia para criar e vender um site", category: "Guias", order: 32, description: "Do briefing à publicação: organize um processo simples para sites de pequenos negócios.", introduction: "Sites vendáveis começam com escopo. Um pacote inicial deve resolver uma necessidade concreta e caber no prazo que você consegue cumprir.", steps: ["Faça briefing.", "Defina sitemap e conteúdo.", "Crie wireframe mobile.", "Desenvolva e teste.", "Apresente prévia.", "Colete aceite e publique.", "Registre manutenção."], examples: "Pacote com início, serviços, sobre, contato, mapa, WhatsApp, SEO básico e duas rodadas de revisão.", checklist: ["Domínio", "Hospedagem", "Textos", "Imagens autorizadas", "Links", "Formulário", "Backup"], commonMistakes: ["Não combinar domínio.", "Não testar celular.", "Prometer SEO garantido."], tips: ["Use componentes reutilizáveis.", "Tenha checklist de entrega."], conclusion: "Um processo repetível vale mais do que uma proposta cheia de recursos que você não consegue manter.", active: true
  },
  {
    id: "guia-servicos-digitais", title: "Guia para vender serviços digitais", category: "Guias", order: 33, description: "Escolha uma entrega, encontre um público e transforme execução em pacote claro.", introduction: "Serviço digital precisa de problema, público, processo e limite. Quanto mais clara a entrega, mais fácil explicar e revisar.", steps: ["Liste habilidades.", "Escolha problema frequente.", "Crie uma amostra.", "Defina pacote básico e opcional.", "Teste abordagem.", "Faça proposta.", "Documente entrega."], examples: "Pacote de conteúdo: pauta, oito legendas, quatro roteiros e revisão mensal.", checklist: ["Público", "Problema", "Entregáveis", "Prazo", "Revisões", "Preço", "Canal de suporte"], commonMistakes: ["Vender disponibilidade ilimitada.", "Misturar serviços sem prioridade.", "Não cobrar por urgência."], tips: ["Comece com um pacote de teste.", "Atualize preço após medir esforço."], conclusion: "A clareza do pacote reduz negociação confusa e melhora a experiência dos dois lados.", active: true
  },
  {
    id: "guia-celular", title: "Guia para começar usando apenas o celular", category: "Guias", order: 34, description: "Organize estudo, portfólio, prospecção e entrega com ferramentas acessíveis no celular.", introduction: "É possível iniciar com o celular, desde que você escolha entregas compatíveis com seus recursos e mantenha organização de arquivos e prazos.", steps: ["Crie pastas para clientes e modelos.", "Use notas para briefing e checklist.", "Monte portfólio simples em página ou PDF.", "Pratique em projetos próprios.", "Faça contatos em horários definidos.", "Use armazenamento em nuvem e backup.", "Melhore equipamento conforme a demanda."], examples: "Serviços compatíveis: roteiros, legendas, artes simples, pesquisa, revisão e páginas leves usando ferramentas online.", checklist: ["E-mail profissional", "Pasta na nuvem", "Modelo de proposta", "Calendário", "Aplicativo de edição", "Backup"], commonMistakes: ["Trabalhar sem backup.", "Aceitar edição pesada sem equipamento.", "Misturar arquivos de clientes."], tips: ["Use teclado externo se possível.", "Defina blocos de foco."], conclusion: "O celular pode ser ponto de partida; escolha escopo que preserve qualidade e evolua conforme a receita real.", active: true
  },
  {
    id: "guia-renda-zero", title: "Guia para montar uma renda online do zero", category: "Guias", order: 35, description: "Um mapa de habilidades, oferta, prospecção, entrega e melhoria contínua sem promessas de ganho garantido.", introduction: "Renda online é construção de competência e relacionamento. O caminho pode levar tempo e os resultados variam; use metas de atividade, não promessas de dinheiro.", steps: ["Escolha uma habilidade útil.", "Estude um nicho.", "Crie uma oferta simples.", "Faça um projeto de demonstração.", "Converse com potenciais clientes.", "Entregue e peça feedback.", "Reinvista parte do que entrar em ferramentas e aprendizado."], examples: "Meta inicial: completar uma amostra, conversar com dez negócios e revisar a oferta com base nas respostas.", checklist: ["Habilidade", "Nicho", "Oferta", "Amostra", "Lista", "Mensagens", "Registro de resultados"], commonMistakes: ["Comprar várias ferramentas antes de validar.", "Trocar de ideia diariamente.", "Acreditar em renda garantida."], tips: ["Revise semanalmente.", "Aprenda com recusas respeitosas.", "Separe receita, custos e reserva."], conclusion: "Consistência e aprendizado prático são mais sustentáveis do que atalhos e promessas.", active: true
  }
];

const prompts = [
  ["briefing-site-local", "Briefing de site para negócio local", "Sites", "Crie um briefing objetivo para um site de [tipo de negócio] em [cidade]. Faça perguntas sobre público, serviços, diferenciais, horário, localização, contatos, fotos, identidade visual, tom de voz, concorrentes e chamada para ação. Organize em seções e marque o que é obrigatório.", "Envie as respostas do cliente e substitua os campos entre colchetes.", "Um briefing com perguntas organizadas e prioridades de conteúdo."],
  ["oferta-servico", "Montar oferta de serviço", "Vendas", "Com base nestes dados: habilidade [habilidade], público [público], problema [problema] e prazo [prazo], proponha três pacotes de serviço. Para cada um, informe entregáveis, limites, dependências do cliente, revisões e uma faixa de preço para validação. Não prometa resultados financeiros.", "Use antes de conversar com potenciais clientes e revise os preços conforme seu esforço real.", "Três opções comparáveis, com escopo e limites claros."],
  ["auditoria-instagram", "Auditoria prática de perfil", "Prospecção", "Analise este perfil de negócio [descrição ou texto público] e liste até cinco melhorias observáveis em bio, oferta, contato, prova e conteúdo. Seja respeitoso, não invente dados e transforme cada ponto em sugestão de baixo custo.", "Cole apenas informações públicas e remova dados pessoais desnecessários.", "Uma lista priorizada de melhorias que pode iniciar uma conversa."],
  ["calendario-conteudo", "Calendário de conteúdo mensal", "Conteúdo", "Crie um calendário de 20 ideias para [nicho], dividido em educação, bastidores, prova, relacionamento e oferta. Para cada ideia, informe formato, gancho, roteiro curto, CTA e recurso necessário. Evite promessas garantidas e repetições.", "Informe o objetivo do mês e os formatos disponíveis.", "Uma pauta organizada que o cliente consegue produzir."],
  ["legenda-reels", "Legenda e roteiro de Reels", "Conteúdo", "Escreva três roteiros de vídeo de até [duração] segundos para [nicho] sobre [tema]. Cada roteiro deve ter gancho, três pontos, encerramento, CTA e legenda. Use linguagem brasileira simples e sinalize qualquer afirmação que precise de fonte.", "Troque os campos e revise fatos antes de publicar.", "Roteiros curtos, graváveis e com CTA específico."],
  ["proposta-site", "Proposta comercial de site", "Vendas", "Monte uma proposta comercial para [cliente] com objetivo, escopo, páginas, integrações, prazo, etapas de aprovação, duas rodadas de revisão, investimento, condições e itens não incluídos. Use tom profissional e não inclua garantias de tráfego ou vendas.", "Preencha valores e prazos que você realmente consegue cumprir.", "Uma proposta clara e pronta para revisão."],
  ["mensagem-personalizada", "Primeira mensagem personalizada", "Prospecção", "Escreva cinco versões curtas de primeira abordagem para [tipo de negócio]. Use este sinal observado: [sinal]. Apresente [serviço] em uma frase, faça uma pergunta e peça permissão para enviar um exemplo. Não seja insistente nem use urgência falsa.", "Substitua o sinal por uma observação verdadeira.", "Mensagens curtas que abrem conversa sem pressão."],
  ["ideias-servico", "Ideias de serviços possíveis", "Estratégia", "Cruze estas habilidades [habilidades], recursos [recursos], tempo semanal [tempo] e três nichos [nichos]. Gere dez ideias de serviços com problema resolvido, entrega, dificuldade, ferramenta necessária e primeira forma de validação. Priorize ofertas pequenas e realistas.", "Use para escolher uma ideia, não para tentar vender todas.", "Uma matriz de ideias com próximo passo de validação."],
  ["revisao-texto-vendas", "Revisão ética de texto de venda", "Copywriting", "Revise o texto abaixo para clareza, gramática e persuasão responsável. Remova promessas garantidas, urgência artificial, depoimentos sem comprovação e afirmações vagas. Preserve benefícios que possam ser comprovados e sugira uma CTA clara. Texto: [cole aqui].", "Cole o texto e confira todas as alterações antes de publicar.", "Uma versão mais clara, honesta e específica."],
  ["checklist-entrega", "Checklist de entrega ao cliente", "Operação", "Crie um checklist de entrega para o serviço [serviço] com arquivos finais, acessos, instruções, aprovação, backup, limites de suporte e pedido de feedback. Separe tarefas do prestador e do cliente.", "Adapte ao escopo vendido.", "Checklist pronto para reduzir esquecimentos e retrabalho."]
].map(([id,title,category,prompt,instructions,example], index) => ({id,title,category,prompt,instructions,example,active:true,order:index+1}));

const tools = [
  ["gerador-ideias-servicos","Gerador de ideias de serviços","Estratégia","Cruze habilidade, nicho e problema para encontrar ofertas pequenas.","Preencha os dados no prompt 'Ideias de serviços possíveis' e escolha uma ideia para validar com conversas reais."],
  ["calculadora-preco","Calculadora de preço de serviço","Finanças","Estime um preço inicial considerando horas, custos e margem de segurança.","Use: (horas × valor-hora) + custos diretos. Compare com o escopo e ajuste após medir o trabalho."],
  ["calculadora-meta-renda","Calculadora de meta de renda","Finanças","Converta uma meta mensal em quantidade aproximada de vendas.","Divida a meta pelo preço líquido esperado e arredonde para cima. Considere custos e meses com menor demanda."],
  ["calculadora-vendas","Calculadora de vendas necessárias","Finanças","Descubra quantas vendas ou clientes são necessários para uma meta.","Informe ticket médio e meta. Use o resultado para planejar prospecção, sem tratar como garantia."],
  ["gerador-proposta","Gerador de proposta","Vendas","Estruture objetivo, entregáveis, prazo, revisões e condições.","Use o prompt de proposta e revise tudo com o cliente antes de enviar."],
  ["gerador-mensagem","Gerador de mensagem para cliente","Prospecção","Crie mensagens curtas a partir de uma observação real.","Personalize o nome, sinal observado e serviço. Respeite quem não quiser receber contato."],
  ["checklist-site","Checklist de criação de site","Operação","Não esqueça briefing, conteúdo, links, formulário, mobile e publicação.","Marque cada item em uma nota ou planilha durante o projeto."],
  ["checklist-prospeccao","Checklist de prospecção","Prospecção","Organize pesquisa, contato, follow-up e registro de respostas.","Trabalhe com uma lista pequena, pública e relevante."],
  ["planejador-conteudo","Planejador de conteúdo","Conteúdo","Monte pautas por objetivo e pilar para uma semana ou mês.","Combine educação, bastidores, prova, relacionamento e oferta."],
  ["calculadora-comissao","Calculadora de comissão","Finanças","Estime comissão bruta e líquida de uma venda afiliada.","Multiplique preço elegível pela taxa de comissão e desconte taxas informadas pelo programa."]
].map(([id,name,category,description,instructions], index) => ({id,name,category,description,instructions,active:true,order:index+1}));

const categories = [
  ["metodos-renda","Métodos de renda","Serviços e estratégias para começar com entregas práticas."],
  ["central-ia","Central de IA","Fluxos e prompts para usar inteligência artificial com revisão."],
  ["clientes","Clientes","Prospecção, abordagem, follow-up e fechamento."],
  ["guias","Guias","Planos completos para organizar execução e aprendizado."],
  ["financas","Finanças","Cálculos e decisões de preço sem promessas de ganho."],
  ["operacao","Operação","Checklists e processos de entrega."],
  ["conteudo","Conteúdo","Planejamento e produção para redes e negócios."]
].map(([id,name,description], index) => ({id,name,description,active:true,order:index+1}));

const challenges = [
  {id:"desafio-7-dias-primeiro-cliente",name:"Desafio 7 dias — Primeiro Cliente",duration:"7 dias",objective:"Sair da ideia e executar uma primeira rodada de validação e prospecção.",description:"Uma semana de tarefas curtas para escolher serviço, preparar oferta, criar demonstração e conversar com potenciais clientes.",steps:["Dia 1 — escolha um serviço que você consiga entregar.","Dia 2 — prepare uma oferta com escopo e preço inicial.","Dia 3 — crie um portfólio ou demonstração.","Dia 4 — encontre potenciais clientes relevantes.","Dia 5 — faça prospecção personalizada.","Dia 6 — faça follow-up respeitoso.","Dia 7 — analise respostas e melhore a oferta."],active:true,order:1},
  {id:"desafio-30-dias-renda-online",name:"Desafio 30 dias — Construindo sua Renda Online",duration:"30 dias",objective:"Criar rotina de estudo, oferta, prospecção e melhoria contínua.",description:"Trinta tarefas progressivas para construir uma base realista, sem promessa de resultado garantido.",steps:["Dia 1 — liste habilidades e recursos.","Dia 2 — escolha um nicho.","Dia 3 — pesquise cinco problemas do nicho.","Dia 4 — escolha uma entrega pequena.","Dia 5 — estude referências.","Dia 6 — crie a primeira amostra.","Dia 7 — peça feedback.","Dia 8 — ajuste a oferta.","Dia 9 — escreva escopo e limites.","Dia 10 — defina preço inicial.","Dia 11 — crie uma proposta.","Dia 12 — organize portfólio.","Dia 13 — faça lista de dez empresas.","Dia 14 — personalize cinco contatos.","Dia 15 — envie as mensagens.","Dia 16 — registre respostas.","Dia 17 — faça follow-up.","Dia 18 — converse com interessados.","Dia 19 — revise objeções.","Dia 20 — melhore o exemplo.","Dia 21 — envie uma proposta.","Dia 22 — pratique a apresentação.","Dia 23 — organize arquivos.","Dia 24 — entregue um exercício ou piloto.","Dia 25 — peça feedback.","Dia 26 — documente o processo.","Dia 27 — calcule esforço e custos.","Dia 28 — atualize o preço.","Dia 29 — planeje a próxima semana.","Dia 30 — faça uma revisão e escolha o próximo foco."],active:true,order:2}
];

const notices = [
  {id:"bem-vindo-renda-mobile",title:"Bem-vindo ao Renda Mobile",message:"Comece explorando os Métodos de renda e escolha uma tarefa prática para hoje.",type:"informacao",priority:"alta",active:true,order:1},
  {id:"comece-desafio-7-dias",title:"Comece pelo desafio de 7 dias",message:"O desafio foi criado para transformar estudo em execução: escolha um serviço, prepare uma oferta e converse com potenciais clientes.",type:"sucesso",priority:"normal",active:true,order:2},
  {id:"novos-conteudos-disponiveis",title:"Novos conteúdos disponíveis",message:"A Central de IA, Clientes, Guias, Ferramentas e Biblioteca já têm materiais iniciais para você estudar e aplicar.",type:"informacao",priority:"normal",active:true,order:3}
];

async function upsert(collection, rows) {
  const batch = db.batch();
  for (const row of rows) {
    const { id, ...data } = row;
    const ref = db.collection(collection).doc(id);
    batch.set(ref, { ...data, createdAt: now, updatedAt: now }, { merge: true });
  }
  await batch.commit();
  return rows.length;
}

(async () => {
  const counts = {};
  counts.categories = await upsert("categories", categories);
  counts.content = await upsert("content", content);
  counts.prompts = await upsert("prompts", prompts);
  counts.tools = await upsert("tools", tools);
  counts.challenges = await upsert("challenges", challenges);
  counts.notices = await upsert("notices", notices);
  console.log(JSON.stringify({project: serviceAccount.project_id, mode:"idempotent-merge", counts}, null, 2));
  await admin.deleteApp(admin.getApp());
})().catch(async (error) => { console.error(error.message); try { await admin.deleteApp(admin.getApp()); } catch {} process.exit(1); });
